# Generated by Django 4.2.6 on 2023-10-12 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appEstablishment', '0001_initial'),
        ('typeThings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSoccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_players', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('status', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_user', models.IntegerField(null=True)),
                ('updated_user', models.IntegerField(null=True)),
                ('deleted_user', models.IntegerField(null=True)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_field_soccer_establishment', to='appEstablishment.establishment')),
                ('type_field_soccer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_field_soccer', to='typeThings.typefieldsoccer')),
            ],
            options={
                'db_table': 'field_soccers',
            },
        ),
    ]
