# Generated by Django 4.2.6 on 2023-11-18 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeThings', '0002_typestatus'),
        ('modificationHistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyreservation',
            name='status',
        ),
        migrations.AddField(
            model_name='historyestablishment',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historyestablishment',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historyreservation',
            name='type_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_reservation_type_status', to='typeThings.typestatus'),
        ),
    ]
