# Generated by Django 4.2.6 on 2023-11-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modificationHistory', '0002_remove_historyreservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyreservation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
