# Generated by Django 4.2.6 on 2023-10-12 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'type_department',
            },
        ),
        migrations.CreateModel(
            name='TypeFieldSoccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('status', models.BooleanField(verbose_name=False)),
            ],
            options={
                'db_table': 'type_field_soccer',
            },
        ),
        migrations.CreateModel(
            name='TypeProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('ubigeo', models.CharField(max_length=10)),
                ('complete', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_departament', to='typeThings.typedepartament')),
            ],
            options={
                'db_table': 'type_province',
            },
        ),
        migrations.CreateModel(
            name='TypeDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('ubigeo', models.CharField(max_length=10)),
                ('complete', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_province', to='typeThings.typeprovince')),
            ],
            options={
                'db_table': 'type_district',
            },
        ),
    ]
