# Generated by Django 4.2.6 on 2023-11-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typeThings', '0002_typestatus'),
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name_emergency_contact',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_emergency_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_dep', to='typeThings.typedepartament'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_dist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_dist', to='typeThings.typedistrict'),
        ),
        migrations.AddField(
            model_name='user',
            name='type_prov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_type_prov', to='typeThings.typeprovince'),
        ),
    ]
