# Generated by Django 4.2.6 on 2023-11-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEstablishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
