# Generated by Django 4.2.6 on 2023-10-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appUser', '0001_initial'),
        ('appFieldSoccer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('status', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_user', models.IntegerField(null=True)),
                ('updated_user', models.IntegerField(null=True)),
                ('deleted_user', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_customer', to='appUser.user')),
                ('field_soccer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_field_soccer', to='appFieldSoccer.fieldsoccer')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
