# Generated by Django 4.2.6 on 2023-11-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReservation', '0002_remove_reservation_status_reservation_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
